###############################################################################
#
#
#
###############################################################################
include $(ONL)/make/config.mk
MODULE := x86_64_cel_questone_2a
AUTOMODULE := x86_64_cel_questone_2a
include $(BUILDER)/definemodule.mk
